## mybatis-configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

## spring-boot-configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/dbAcount  # 数据库连接地址, 文件模式
    username: dbAdmin
    password: 1qaz@WSX
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/db-schema.sql # 每次启动时执行ddl
      data-locations: classpath*:sql/data.sql        # 每次启动时执行dml

## logging-configuration
logging:
  level:
    root: INFO