## mybatis-configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

## spring-boot-configuration
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=UTC
    username: dbAdmin
    password: 1qaz@WSX
    maxWait: 1800000

## logging-configuration
logging:
  level:
    root: INFO